title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/abc-skeleton-root"
url: "https://studiobvio.github.io"
twitter_username: studiobvio
github_username: studiobvio

repository: "studiobvio/abc-skeleton"

plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - github-pages
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: expanded
#  destination: ./site

autoprefixer:
  browsers:
    - last 4 versions
#    - Safari > 2

collections:
  profiles:
    output: true
    label: "Profiles"
  resources:
    output: true
    label: "Resource"
  posts:
    output: true
    label: "Post"
  ideas:
    output: true
    label: "Ideas"
